authorization/urls.py
from django.urls import path
from .views import RegisterView, IndexView, ProfileEditView, user_login, logout_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authorization'

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", user_login, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("edit_profile/", ProfileEditView.as_view(), name="edit_profile"),
    # path('register', RegisterView.as_view(),  name='register'),
]

config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="authorization/")),
    path('authorization/', include('authorization.urls', namespace='authorization')),
    path('technologist/', include('technologist.urls', namespace='technologist')),
]

mechanic/urls.py
from django.contrib import admin
from django.urls import path
from .views import IndexView


app_name = 'mechanic'

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

authorization/models.py
from tkinter.tix import Tree
from django.contrib.auth.models import UserManager, PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models


class CustomUser(AbstractBaseUser, PermissionsMixin):
    clock_number = models.IntegerField(primary_key=Tree, verbose_name='табельный номер')
    login_validator = ASCIIUsernameValidator()
    username = models.CharField(max_length=128, unique=True, 
        help_text = ('Не больше 128 символов цифры и латинские буквы'),
        validators = [login_validator], verbose_name='Логин',
        error_messages= {"unique": ("Пользователь с таким логином уже существует")})
    password = models.CharField(verbose_name='Пароль', max_length=256)
    first_name = models.CharField(verbose_name='имя', max_length=128, blank=False)
    last_name = models.CharField(verbose_name='фамилия', max_length=128, blank=False)
    email = models.EmailField(verbose_name='Электронная почта', unique=True)
    phone = models.CharField(verbose_name='Номер телефона в формате 9.. ... .. ..', max_length=10)
    date_of_birth = models.DateField(verbose_name='День рождения', null=True)
    is_active = models.BooleanField(default=True)
    is_technologist = models.BooleanField(default=False, verbose_name='Технолог')
    is_mechanic = models.BooleanField(default=False, verbose_name='механик')
    creation_date = models.DateField(auto_now_add=True, verbose_name='дата прихода на предприятие/создание записи')
    is_staff = models.BooleanField(default=True)
    bonus_procent = models.PositiveSmallIntegerField(default=0, verbose_name='процент премии')
    next_knowledge_check = models.DateField(null=True, verbose_name='следующая ежегодная проверка знаний')

    objects = UserManager()
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ['first_name', 'phone']
    EMAIL_FIELD = "email"

    class Meta:
        verbose_name = ('пользователь')
        verbose_name_plural = ('пользователи')



    def get_name(self):
        return self.first_name

    def make_active(self):
        self.is_active = True
        self.save()
    
    def delete(self):
        self.is_active = False
        self.save()

    def make_technologist(self, val=True):
        self.is_technologist = val

    def make_mechanic(self, val=True):
        self.is_mechanic = val

authorization/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from django import forms


class CustomUserCreationForm(UserCreationForm):
    field_order =[
        'username',
        'password1',
        'password1',
        'first_name',
        'last_name',
        'email',
        'phone',
        'date_of_birth',
    ]
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'phone',
            'date_of_birth',
            )
        field_classes = {'username': UsernameField}


class CustomUserChangeForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'phone',
            'date_of_birth',
            )
        field_classes = {"username": UsernameField}

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    

authorization/views.py
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic.edit import FormView
from django.views.generic import ListView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .forms import LoginForm
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.contrib.auth import logout
from .forms import CustomUserCreationForm, CustomUserChangeForm, LoginForm
from .models import CustomUser
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login as log_in

class IndexView(TemplateView):
    template_name = 'authorization/index.html'

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,  username=cd['username'],  password=cd['password'])

        if user is not None:
            if user.is_active:
                log_in(request, user)
               
                return  render(request, 'authorization/index.html', {'form': form})
            else:
                
                return render(request, 'authorization/bad_account.html')
        else:
            
            return render(request, 'authorization/bad_login.html')
    else:
        form = LoginForm()
    return render(request, 'authorization/login.html', {'form': form})





class CustomLogoutView(LogoutView):

    def dispatch(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, _("Совершен выход!"))
        return super().dispatch(request, *args, **kwargs)

def logout_view(request):
    logout(request)
    return render(request, 'authorization/index.html')

class ProfileEditView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = CustomUserChangeForm

    def test_func(self):
        return True if self.request.user.pk == self.kwargs.get("pk") else False
    
    def get_success_url(self):
        return reverse_lazy("authorization:edit_profile", args=[self.request.user.pk])



class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'authorization/register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('authorization:index')

authorization/templates/authorization/bad_account.html
{% extends 'authorization/base.html' %}


{% block content %}
<p>Неактивынй аккаунт</p>
{% endblock content %}

authorization/templates/authorization/bad_login.html
{% extends 'authorization/base.html' %}


{% block content %}
<div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
        <div class="modal-header border-bottom-0">
            <h5 class="modal-title">Ошибка входа</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-0">
            <p>Войти не получилось т.к. неверно введен логин или пароль</p>
        </div>
        <div class="modal-footer flex-column border-top-0">
            <a href="{% url 'authorization:login' %}"><button type="button"
                    class="btn btn-lg btn-primary w-100 mx-0 mb-2">Страница входа</button></a>
            <a href="{% url 'authorization:index' %}"><button type="button" class="btn btn-lg btn-light w-100 mx-0"
                    data-bs-dismiss="modal">Главная</button></a>

        </div>
    </div>
</div>
{% endblock content %}

authorization/templates/authorization/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    {% include 'authorization/overall/head.html' %}
    <br><br><br>
    {% block content %}
    <p>Ничего не передано из базового шаблона</p>
    {% endblock content %}

</body>

</html>

authorization/templates/authorization/index.html
{% extends 'authorization/base.html' %}


{% block content %}
<br><br><br>
<div class="row mb-2">
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">Обучение</strong>
                <h3 class="mb-0">Стажер</h3>
                <p class="card-text mb-auto">Обучение работы на текущей технологии без доступа к регулировке параметров
                </p>

                <a href="{% url 'technologist:index' %}" class="stretched-link"></a>

            </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" role="img" aria-label="Placeholder: Thumbnail"
                    preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#ddd6d7" style="--darkreader-inline-fill: #ddd6d7;"
                        data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#ddd6d7" dy=".3em"
                        style="--darkreader-inline-fill: #ddd6d7;" data-darkreader-inline-fill="">Thumbnail</text>
                </svg>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">Контроль технологических операций</strong>
                <h3 class="mb-0">Технолог</h3>
                <p class="mb-auto">Работа с технологией</p>
                {% if not user.is_technologist %}
                <div class="mb-1 text-muted">Для входа необходимо залогиниться</div>
                <a href="{% url 'authorization:login' %}" class="stretched-link"></a>

                {% else %}
                <a href="{% url 'technologist:index' %}" class="stretched-link"></a>
                {% endif %}

            </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" role="img" aria-label="Placeholder: Thumbnail"
                    preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c" style="--darkreader-inline-fill: #b0a99f;"
                        data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"
                        style="--darkreader-inline-fill: #dddad6;" data-darkreader-inline-fill="">Thumbnail</text>
                </svg>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">Просмотр позиций для ремонта</strong>
                <h3 class="mb-0">Механик</h3>
                <p class="mb-auto">Ремонт оборудования и все что с ним связано</p>
                {% if not user.is_mechanic %}
                <div class="mb-1 text-muted">Для входа необходимо залогиниться</div>
                <a href="{% url 'authorization:login' %}" class="stretched-link"></a>
                {% else %}
                <a href="{% url 'mechanic:index' %}" class="stretched-link"></a>
                {% endif %}

            </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" role="img" aria-label="Placeholder: Thumbnail"
                    preserveAspectRatio="xMidYMid slice" focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c" style="--darkreader-inline-fill: #9fb09f;"
                        data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"
                        style="--darkreader-inline-fill: #dddad6;" data-darkreader-inline-fill="">Thumbnail</text>
                </svg>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

authorization/templates/authorization/login.html
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<body class="text-center">
    <main class="form-signin w-100 m-auto"></main>
    <form method="post">
        {% csrf_token %}
        <img class="mb-4" src="{% static '/images/logo/logo.png' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Вход</h1>

        <ul>
            {{ form|crispy }}
        </ul>

        <div class="checkbox mb-3">
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
    </form>
    <a href="{% url 'authorization:index' %}"><button type="button" class="btn2 btn-error">Главная</button></a>
    </main>
</body>

{% endblock content %}

authorization/templates/authorization/register.html
{% extends 'authorization/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<main>



    <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static '/images/logo/logo.png' %}" alt="" width="72" height="57">
        <h2>Регистрация нового пользователя</h2>
        <p class="lead">Регистрация необходима один раз для использования всех функций Технолог или Ремонтник</p>
    </div>

    <div class="row g-5">
        <form method="post" class="mt-2" enctype="multipart/form-data">
            {% csrf_token %}
            <h4 class="mb-3"> </h4>
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
        </form>
    </div>
</main>










{% endblock content %}