config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url="authorization/")),
    path('authorization/', include('authorization.urls', namespace='authorization')),
    path('technologist/', include('technologist.urls', namespace='technologist')),
]

technologist/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import IndexView, H701View

app_name = 'technologist'

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    # path("H701/", H701View.as_view(), name="H701"),
    path('H701/', H701View.as_view(),  name='H701'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

technologist/models.py
from importlib.resources import path
from authorization.models import CustomUser
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import Thumbnail

class Blocs(models.Model):
    id = models.AutoField(primary_key=True)
    min_description = models.CharField(max_length=30, verbose_name='название блока')
    max_description = models.CharField(null=True, max_length=256, verbose_name='полная расшифровка')

class Aggregates(models.Model):
    id = models.AutoField(primary_key=True)
    block_id = models.OneToOneField(Blocs, on_delete=models.PROTECT)
    num_in_block = models.PositiveSmallIntegerField()
    abb = models.CharField(max_length=2, verbose_name='буква обозначения функциональной работы')
    description = models.CharField(max_length=30, verbose_name='расшифровка названия')
    next_revision_date = models.DateField()
    next_comprehensive_test = models.DateField()


class Aggregat_func(models.Model):
    id = models.AutoField(primary_key=True)
    abb = models.CharField(max_length=2, verbose_name='буква обозначения функции агрегата')
    description = models.CharField(max_length=20, verbose_name='расшифровка названия')

class Params(models.Model):
    id = models.AutoField(primary_key=True)
    abb = models.CharField(max_length=5, verbose_name='букваы полная расшифровка прибора')
    description = models.CharField(max_length=20, verbose_name='расшифровка названия')

class Devices(models.Model):
    id = models.AutoField(primary_key=True)
    block_id = models.OneToOneField(Blocs, on_delete=models.PROTECT)
    aggregate_id = models.OneToOneField(Aggregates, on_delete=models.PROTECT)
    aggregat_func = models.OneToOneField(Aggregat_func, on_delete=models.PROTECT)
    num_in_aggregat = models.PositiveSmallIntegerField(null=True)
    param = models.OneToOneField(Params, on_delete=models.PROTECT)
    socket = models.FileField(verbose_name='путь к сокету')
    crytiсal_high= models.IntegerField(null=True, default=None)
    high = models.IntegerField(null=True, default=None)
    low = models.IntegerField(null=True, default=None)
    crytiсal_low = models.IntegerField(null=True, default=None)
    next_revision_date = models.DateField()
    alarm = models.BooleanField(default=False)
    # number_of_measurements = models.IntegerField(default=604800)


class History_Params(models.Model): # может как то переработать чтобы каждый раз не указывать время
    device_id = models.OneToOneField(Devices, on_delete=models.PROTECT)
    pv = models.PositiveSmallIntegerField(null=True, default=None)
    op = models.PositiveSmallIntegerField(null=True, default=None)
    sp =models.PositiveSmallIntegerField(null=True, default=None)
    time = models.DateTimeField()

class Defects(models.Model):
    id = models.AutoField(primary_key=True)
    defect_device = models.OneToOneField(Devices, null=True, default=None, on_delete=models.PROTECT)
    defect_aggregate = models.OneToOneField(Aggregates, null=True, default=None, on_delete=models.PROTECT)
    comment = models.CharField(max_length=512)
    who_find_defect = models.OneToOneField(CustomUser, on_delete=models.PROTECT)
    now_mechanic = models.DateTimeField(auto_now_add=True)
    now_electrician = models.DateTimeField(auto_now_add=True)
    now_KIP = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    planned_fix_it = models.DateTimeField()
    factual_fix_it = models.DateTimeField()


import PIL
from PIL import Image
from imagekit.models.fields import ImageSpecField
from imagekit.processors import ResizeToFit, Adjust,ResizeToFill


class Jobseeker(models.Model):
    photo = models.ImageField(verbose_name='Poster', upload_to='media/schems/')

technologist/views.py
from urllib import request
from django.views.generic import TemplateView, DetailView, CreateView
from django.shortcuts import render

from .models import Jobseeker
from .form import JobseekerForm


class IndexView(TemplateView):
    template_name = 'technologist/index.html'


class H701View(CreateView):
    model = Jobseeker
    form_class = JobseekerForm
    content = Jobseeker.objects.all()
    template_name ='technologist/H701.html'

technologist/templates/technologist/H701.html
{% extends "technologist/base.html" %}

{% block content %}

{% for b in data %}
<a href="{{ b.book.url }}">{{ b.title }}</a>
<img src="{{ b.cover.url }}">
{% endfor %}

{% endblock content %}

technologist/templates/technologist/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
    {% include 'technologist/overall/schem_head.html' %}
    {% block content %}
    <p>Пустой базовый шаблон</p>

    {% endblock content %}
</body>

</html>

technologist/templates/technologist/index.html
{% extends 'authorization/base.html' %}
{% load static %}

{% block content %}





<div class="album py-5 bg-light">
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <a href="{% url 'technologist:H701' %}">
                        <img src="{% static 'images/mini/schems.jpeg' %}" width="300" height="180" alt="schems">
                        <div class="card-body">
                            <p class="card-text">Технологические схемы</p>
                            <div class="d-flex justify-content-between align-items-center">

                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a href="">
                        <img src="{% static 'images/mini/interlock.png' %}" width="300" height="180"
                            alt="safety interlock">
                        <div class="card-body">
                            <p class="card-text">Блокировки технологического режима</p>
                            <div class="d-flex justify-content-between align-items-center">


                            </div>

                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <a href="">
                        <img src="{% static 'images/mini/trends.png' %}" width="300" height="180" alt="trends">
                        <div class="card-body">
                            <p class="card-text">Тренды ведения технологического режима</p>
                            <div class="d-flex justify-content-between align-items-center">


                            </div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                    <a href="">
                        <img src="{% static 'images/mini/mode.png' %}" width="300" height="180" alt="mode">
                        <div class="card-body">
                            <p class="card-text">Программы каскадных режимов</p>
                            <div class="d-flex justify-content-between align-items-center">

                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                        xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c" style="--darkreader-inline-fill: #43484b;"
                            data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"
                            style="--darkreader-inline-fill: #dddad6;" data-darkreader-inline-fill="">Thumbnail</text>
                    </svg>

                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                            additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                        xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c" style="--darkreader-inline-fill: #43484b;"
                            data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"
                            style="--darkreader-inline-fill: #dddad6;" data-darkreader-inline-fill="">Thumbnail</text>
                    </svg>

                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                            additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                        xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                        preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c" style="--darkreader-inline-fill: #43484b;"
                            data-darkreader-inline-fill=""></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em"
                            style="--darkreader-inline-fill: #dddad6;" data-darkreader-inline-fill="">Thumbnail</text>
                    </svg>

                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                            additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}